server:
  port: 5555
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
            allowedHeaders: "*"
      routes:
          - id:   core-service
            uri:  http://localhost:8189
            predicates:
              - Path=/core/**
            filters:
              - StripPrefix=1
              - PrefixPath=/market_spring_core
              - JwtAuthFilter
          - id: cart-service
            uri: http://localhost:8190
            predicates:
              - Path=/cart/**
            filters:
              - StripPrefix=1
              - PrefixPath=/market_spring_cart
              - JwtAuthFilter
          - id: auth-service
            uri: http://localhost:8188
            predicates:
              - Path=/auth/**
            filters:
              - StripPrefix=1
              - PrefixPath=/market_spring_auth
              - JwtAuthFilter

jwt:
  secret: sdlf23nDwe1orJh23ou-3[2k',wPe;fd-ac43arqE3tuil
  lifetime: 3600000

#           http://localhost:5555/core/api/v1/products -> http://localhost:8189/market_spring_core/api/v1/products