server:
  port: 8190
  servlet:
    context-path: /market_spring_carts
integrations:
  product-service:
    url: http://localhost:8189/market_spring_core/
    connect-timeout: 500
    read-timeout: 10000
    write-timeout: 5000
